### ISSUE TITLE
License

### ISSUE THREAD

**Issue by rugk** [theborg3of5/KeepParentTabHistory#1]
Could you please [choose a](https://choosealicense.com/) [license](https://help.github.com/articles/open-source-licensing/) and [add it to your repo](https://help.github.com/articles/open-source-licensing/#where-does-the-license-live-on-my-repository)?

I may want to revive your extension.

**Comment by theborg3of5** [comment]
I've added a new LICENSE.md file to the repo with the MIT license in 521b0b76197466fa5db2161640906396c83a13ba.

Please feel free to use what I have here, but fair warning (from the README.md):
**Note: this extension has been discontinued, waiting on a resolution of this issue (https://code.google.com/p/chromium/issues/detail?id=41321) or some other manner in which to access the history of a specific tab in Chrome.**
